import Image from "next/image";

// Static brand mark — frozen halftone "pose" generated by
// `scripts/generate-halftone-mark.mjs`. The SVG is committed to
// `public/halftone-mark.svg` so the runtime cost is zero.
//
// Re-run the script with a fresh SEED if you want a new pose.

type Props = {
  size?: number;
  className?: string;
  alt?: string;
};

export function HalftoneMark({ size = 28, className, alt = "Officehours" }: Props) {
  return (
    <Image
      src="/halftone-mark.svg"
      width={size}
      height={size}
      alt={alt}
      className={className}
      priority
    />
  );
}
